export const ROUTES = {
    LANDING: '/',
    MENU: '/carta',
    PRIVACY_POLICY: '/politica-privacidad',
    LOGIN: '/login',
    REGISTER: '/registro',
    DASHBOARD: '/dashboard',
    ADMIN_PRODUCTOS: '/admin/productos',
    ADMIN_CATEGORIAS: '/admin/categorias',
    ADMIN_MESAS: '/admin/mesas',
    ADMIN_RESERVAS: '/admin/reservas',
    ADMIN_PEDIDOS: '/admin/pedidos',
    ADMIN_USUARIOS: '/admin/usuarios',
    CLIENTE_PEDIDO: '/pedido-cliente/:token',
    REDSYS_MOCK: '/pago-redsys/:pedidoId',
    PERFIL: '/perfil',
    KITCHEN: '/cocina',
    STAFF: '/personal-sala',
    WAITER_ORDER: '/camarero/comanda/:mesaId',
    RESERVA_CLIENTE: '/reservar',
    SCAN_QR: '/escanear-qr',
};
