spring.application.name=restnova

# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/restaurantedb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT (Este secreto debe ser configurado desde variables de entorno idealmente)
# Secret para local
jwt.secret=TuClaveSecretaDeAdecuadaLongitud


logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG